language: node_js
node_js: 
  - 12

services:
  - docker 

# Pre-testing installs unused
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests 
before_script:
  - echo "no tests"

# Scripts
script: 
  - docker --version # print the docker version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed isaiahtech/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user isaiahtech/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend isaiahtech/udagram-frontend:v1

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy isaiahtech/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push isaiahtech/udagram-api-feed:v1
  - docker push isaiahtech/udagram-api-user:v1
  - docker push isaiahtech/udagram-frontend:v1
  - docker push isaiahtech/udagram-reverseproxy:v1